spring:
  #静态资源处理
  resources:
    #默认启用静态资源处理
    add-mappings: true
    cache:
      cachecontrol:
        #缓存相应时间，单位秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      #启用资源链 默认禁用
      enabled: true
      #启用压缩资源（gzip,brotli)解析，默认禁用
      compressed: true
      #启用H5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接出
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1000000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的链接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1000000（30分钟）
      max-lifetime: 1000000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 心跳机制：测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  #redis配置
  redis:
    port: 6379
#    host: 192.168.78.187
    host: 127.0.0.1
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小默认连接，默认0
        min-idle: 5
  # rabbitmq
  rabbitmq:
    #服务器
    host: 192.168.78.188
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完再继续下一条
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发起重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认三次
        max-attempts: 3
        #重试最大时间间隔，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如2.0：第一次等10s，第二次20s，第三次40s
        multiplier: 1




mybatis-plus:
  # 配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.shawn.seckill.pojo

# mybatis SQL打印（方法接口所在的包，不是mapper.xml)
logging:
  level:
    com.shawn.seckill.mapper: debug